# Generated by Django 5.1.15 on 2026-05-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('ingestion_method', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_jobs', to='ingestion.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('normalized', 'Normalized'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('upload_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.uploadjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['organization', 'source_type'], name='ingestion_d_organiz_c6b96d_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadjob',
            index=models.Index(fields=['upload_status'], name='ingestion_u_upload__d4f1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadjob',
            index=models.Index(fields=['uploaded_at'], name='ingestion_u_uploade_3502bf_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['processing_status'], name='ingestion_r_process_0d21eb_idx'),
        ),
    ]
