# Generated by Django 5.1.15 on 2026-05-26 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('scope_category', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=10)),
                ('activity_type', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('co2e_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('emission_factor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('record_date', models.DateField()),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'scope_category'], name='emissions_e_organiz_b0f1fe_idx'), models.Index(fields=['source_type'], name='emissions_e_source__067ec8_idx'), models.Index(fields=['approval_status'], name='emissions_e_approva_a4e49b_idx'), models.Index(fields=['record_date'], name='emissions_e_record__e9fb84_idx'), models.Index(fields=['locked'], name='emissions_e_locked_a9b15f_idx')],
            },
        ),
    ]
