# Generated by Django 5.1.15 on 2026-05-26 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='emissions.emissionrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['severity'], name='validation__severit_7c76bf_idx'), models.Index(fields=['resolved'], name='validation__resolve_58c9e5_idx'), models.Index(fields=['emission_record', 'resolved'], name='validation__emissio_ac49ba_idx')],
            },
        ),
    ]
